# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    branches:
      - 'releases/**'
    branches-ignore:
      - '!releases/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name
        
      - uses: alagos/regex-merge@927e66290e16a9b7a565ab29e0d1b574522a4731
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          headBranch: ${{ steps.branch_name.outputs.branch }}
          branchRegex: '^main$'
          
      - uses: dawidd6/action-delete-branch@d1efac9a6f7a9b408d4e8ff663a99c1fbac17b3f
        with:
          branches: ${{ steps.branch_name.outputs.branch }}
