# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    branches:
      - 'releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: alagos/regex-merge@v1.0
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          headBranch: ${GITHUB_REF#refs/heads/}
          branchRegex: '^main$'
